import { defineConfig, type Plugin, type ViteDevServer } from "vite";
import react from "@vitejs/plugin-react";
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";

// Repository root (one level above this frontend/ package).
const REPO_ROOT = path.resolve(__dirname, "..");

// Source directories whose changes require re-running the Python build.
const CONTENT_DIR = path.join(REPO_ROOT, "content");
const SCRIPTS_DIR = path.join(REPO_ROOT, "scripts");
const BUILD_SCRIPT = path.join(SCRIPTS_DIR, "build_content.py");

// File extensions that feed the content pipeline.
const WATCHED_EXTENSIONS = new Set([".md", ".json", ".py"]);

/**
 * Resolve the interpreter that runs scripts/build_content.py. Honor an explicit
 * PYTHON override first (useful for CI / non-standard setups), then prefer the
 * repo-root virtualenv created per the README, and finally fall back to a
 * system python3 so a fresh checkout still live-reloads before the venv exists.
 */
function resolvePython(): string {
  if (process.env.PYTHON) return process.env.PYTHON;
  const venvPosix = path.join(REPO_ROOT, ".venv", "bin", "python");
  const venvWin = path.join(REPO_ROOT, ".venv", "Scripts", "python.exe");
  if (existsSync(venvPosix)) return venvPosix;
  if (existsSync(venvWin)) return venvWin;
  return process.platform === "win32" ? "python" : "python3";
}

/**
 * Dev-server plugin: live-reload on Markdown / JSON / Python content changes.
 *
 * Vite's own HMR already covers the React/TypeScript/CSS sources. What it does
 * not see is the content layer: `content/*.md`, `content/_meta/*.json`, and the
 * `scripts/*.py` that compile them into `public/data/*.json`. This plugin
 * watches those sources, re-runs the build on change (debounced, never
 * overlapping), and pushes a full-reload so the browser re-fetches the
 * regenerated JSON. Active only under `vite dev` (`apply: "serve"`).
 */
function contentLiveReload(): Plugin {
  const python = resolvePython();
  let timer: ReturnType<typeof setTimeout> | null = null;
  let running = false;
  let rerunQueued = false;

  return {
    name: "content-live-reload",
    apply: "serve",
    configureServer(server: ViteDevServer) {
      // The content/scripts dirs live outside Vite's root, so register them
      // with the existing chokidar instance explicitly.
      server.watcher.add([CONTENT_DIR, SCRIPTS_DIR]);

      const runBuild = (): void => {
        if (running) {
          rerunQueued = true;
          return;
        }
        running = true;
        const child = spawn(python, [BUILD_SCRIPT], {
          cwd: REPO_ROOT,
          stdio: ["ignore", "pipe", "pipe"],
        });
        let stderr = "";
        child.stderr.on("data", (chunk) => (stderr += chunk.toString()));
        child.on("error", (err) => {
          running = false;
          server.config.logger.error(
            `[content] failed to launch ${python}: ${err.message}`,
          );
        });
        child.on("close", (code) => {
          running = false;
          if (code === 0) {
            server.config.logger.info("[content] rebuilt → reloading");
            server.ws.send({ type: "full-reload", path: "*" });
          } else {
            server.config.logger.error(
              `[content] build failed (exit ${code})\n${stderr.trim()}`,
            );
          }
          // Coalesce any change that arrived while a build was in flight.
          if (rerunQueued) {
            rerunQueued = false;
            runBuild();
          }
        });
      };

      const schedule = (file: string): void => {
        const inScope =
          (file.startsWith(CONTENT_DIR) || file.startsWith(SCRIPTS_DIR)) &&
          WATCHED_EXTENSIONS.has(path.extname(file));
        if (!inScope) return;
        if (timer) clearTimeout(timer);
        // Small debounce so bulk saves / git operations trigger one build.
        timer = setTimeout(runBuild, 150);
      };

      server.watcher.on("add", schedule);
      server.watcher.on("change", schedule);
      server.watcher.on("unlink", schedule);
    },
  };
}

// Vite config for the portfolio site. The data layer is generated by the
// Python build pipeline into ./public/data/*.json and served as static assets;
// contentLiveReload() keeps that data fresh while `vite dev` is running.
export default defineConfig({
  plugins: [react(), contentLiveReload()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 5173,
    open: false,
  },
});
